name: update forked repo

on:
  schedule:
    - cron: '0 16 * * *'  # 北京时间每周日凌晨执行
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: fetch upstream 
      run: |
        git clone https://github.com/wzdnzd/aggregator.git upstream
        \cp upstream/aggregate/* aggregate/ -a

    - name: rm upstream
      run: |
        rm -rf upstream

    - name: Check_for_changes
      id: check_changes
      run: |
        if git diff-index --quiet HEAD --; then
          echo "0"
          exit 0
        else
          echo "1"
          exit 1
        fi
    
        
    - name: Configure Git
      run: |
        git config user.name "GA Bot"
        git config user.email "actions@github.com"
      
    - name: Commit and push changes
      run: |
        git add aggregate/subscribe
        git commit -m "update repo from upstream" && git push || echo 'No update from upstrea!'
